language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA3TEAFEHHZFBYTDEH"
  secret_access_key:
    secure: "njVDiTG5PRL5bH44oc44hcKZBNiB2Ra6EfcxhP6"
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "the-target-S3-bucket"

script:
  - black .
  - python -m black . --check
  - flake8 .
  # - python -m coverage run --source=. manage.py test
  # - python -m coverage report -m

after_script:
  - coveralls


  