language: ruby
rvm:
 - 2.2
 - jruby
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA3TEAFEHHZFBYTDEH"
  secret_access_key:
    secure: "njVDiTG5PRL5bH44oc44hcKZBNiB2Ra6EfcxhP6"
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "the-target-S3-bucket"
